const data = [
  {
    id: "1",
    dishName: "Pizza - Barbecue",
    cookDuration: "1hr",
    numbOfServing: 3,
    dishImage: require("../assets/images/food_2.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "2",
    dishName: "Creamy tasty pancake",
    cookDuration: "2hr 30mins",
    numbOfServing: 1,
    dishImage: require("../assets/images/food_1.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "3",
    dishName: "Chicken & Chips",
    cookDuration: "1hr 30mins",
    numbOfServing: 4,
    dishImage: require("../assets/images/food_3.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "4",
    dishName: "Burger",
    cookDuration: "30mins",
    numbOfServing: 2,
    dishImage: require("../assets/images/food_1.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "5",
    dishName: "Pasta",
    cookDuration: "1hr 10mins",
    numbOfServing: 3,
    dishImage: require("../assets/images/food_2.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "6",
    dishName: "Hot Spicy Corn Dog",
    cookDuration: "1hr 10mins",
    numbOfServing: 2,
    dishImage: require("../assets/images/food_1.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "7",
    dishName: "Hot Spicy Corn Dog",
    cookDuration: "1hr 10mins",
    numbOfServing: 2,
    dishImage: require("../assets/images/food_1.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
  {
    id: "8",
    dishName: "Hot Spicy Corn Dog",
    cookDuration: "1hr 10mins",
    numbOfServing: 2,
    dishImage: require("../assets/images/food_1.jpg"),
    // isBookmarked: true,
    // ingredient:["onion","ginger","garlic","flour","sauce"],
  },
];
export default data;